spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
eureka:
  client:
    serviceUrl:
      defaultZone: ${services__eureka__https__0}/eureka/
  instance:
    preferIpAddress: true

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
